export const INITIALIZE_APP = 'INITIALIZE_APP';
// booking
export const FILL_ALL_BOOKINGS = 'FILL_ALL_BOOKINGS';
export const ADD_BOOKING = 'ADD_BOOKING';
export const UPDATE_BOOKER_STATUS = 'UPDATE_BOOKER_STATUS';

// trip
export const RESET_TRIP = 'RESET_TRIP';
export const START_TRIP = 'START_TRIP';
export const END_TRIP = 'END_TRIP';

// location
export const UPDATE_ROUTE = 'UPDATE_ROUTE';
export const UPDATE_CURRENT_DISTANCE = 'UPDATE_CURRENT_DISTANCE';
export const UPDATE_STATION_INFO = 'UPDATE_STATION_INFO';

// status
export const TRIP_NOT_STARTED = 'TRIP_NOT_STARTED';
export const TRIP_IN_PROGRESS = 'TRIP_IN_PROGRESS';
export const TRIP_COMPLETED = 'TRIP_COMPLETED';

export const LATENCY_EARLY = 'LATENCY_EARLY';
export const LATENCY_ON_TIME = 'LATENCY_ON_TIME';
export const LATENCY_LATE = 'LATENCY_LATE';
